const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Behaviors.NoSave,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.gamepad,
		C3.Plugins.Browser,
		C3.Plugins.Tilemap,
		C3.Plugins.Audio,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Plugins.GameRecorder,
		C3.Plugins.AJAX,
		C3.Plugins.Particles,
		C3.Plugins.Function,
		C3.Plugins.Greenworks,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.GameRecorder.Cnds.IsRecording,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetFramerateMinMax,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetWave,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Spritefont2.Cnds.CompareX,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Exps.CharacterWidth,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Greenworks.Acts.ActivateAchievement,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Sin.Cnds.CompareWave,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Touch.Exps.XAt,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.gamepad.Exps.GamepadIndex,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.GameRecorder.Cnds.OnRecordingReady,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.GameRecorder.Exps.RecordingURL,
		C3.Plugins.GameRecorder.Acts.StopRecording,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.GameRecorder.Acts.StartRecording,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.gamepad.Cnds.OnGamepadDisconnected,
		C3.Plugins.Greenworks.Cnds.IsOverlayEnabled,
		C3.Plugins.gamepad.Cnds.OnGamepadConnected
	];
};
self.C3_JsPropNameTable = [
	{crono: 0},
	{from: 0},
	{skully: 0},
	{skully2: 0},
	{CollectibleIcon: 0},
	{Necrotitle: 0},
	{loadicon: 0},
	{newicon: 0},
	{buttonmapicon: 0},
	{bigarrow: 0},
	{prop_text_heaven: 0},
	{prop_text_afterlife: 0},
	{prop_count1: 0},
	{prop_text_block: 0},
	{prop_text_tower: 0},
	{prop_text_chasm: 0},
	{prop_chain_big: 0},
	{prop_text_limbo: 0},
	{prop_flooded: 0},
	{prop_line1: 0},
	{BGDogTooth: 0},
	{BGSomething: 0},
	{BGSomething2: 0},
	{BGSomething3: 0},
	{smallarrow: 0},
	{PauseQuit: 0},
	{PauseResume: 0},
	{PauseTitle: 0},
	{Confirm: 0},
	{ConfirmYes: 0},
	{ConfirmNo: 0},
	{prop_text_heaven2: 0},
	{FakeWall: 0},
	{prop_giveup: 0},
	{prop_uarrow: 0},
	{skully3: 0},
	{prop_web: 0},
	{prop_spinner: 0},
	{prop_bunting: 0},
	{prop_spinner_small: 0},
	{prop_fakewall: 0},
	{prop_text_goback: 0},
	{prop_text_welcome: 0},
	{prop_yourehere: 0},
	{Tween: 0},
	{SplashBG: 0},
	{SplashBGFlash: 0},
	{prop_text_the_well: 0},
	{DevNotes: 0},
	{Type: 0},
	{CreditsText: 0},
	{ROLLENDED: 0},
	{ScrollTo: 0},
	{Bullet: 0},
	{creditscamera: 0},
	{CreditsRollStopper: 0},
	{WhiteScreen: 0},
	{Fadout: 0},
	{BlackCurtain: 0},
	{LAST_INPUT_DIRECTION: 0},
	{LAST_INPUT_TIME: 0},
	{LANDING: 0},
	{FLY: 0},
	{SHOOT: 0},
	{EXPLODE: 0},
	{BLUNDER: 0},
	{ROCKET_JUMP: 0},
	{jump: 0},
	{shootInterval: 0},
	{flyX: 0},
	{flyY: 0},
	{maxBulletsOnScreen: 0},
	{speed: 0},
	{gravity: 0},
	{maxFallSpeed: 0},
	{MOVEMENT_ENABLED: 0},
	{VELOCITY_X: 0},
	{VELOCITY_Y: 0},
	{pushbackX: 0},
	{pushbackY: 0},
	{PUSHINGBACK: 0},
	{pushbackDisableMovementDelay: 0},
	{BOUNCYSHOOTER: 0},
	{lastZap: 0},
	{INVULNERABLE: 0},
	{canPortal: 0},
	{MoveTo: 0},
	{Fade: 0},
	{Flash: 0},
	{Timer: 0},
	{Player: 0},
	{Solid: 0},
	{NoSave: 0},
	{Wall: 0},
	{End: 0},
	{snapX: 0},
	{Tag: 0},
	{Sine: 0},
	{Jump: 0},
	{Keyboard: 0},
	{Spawn: 0},
	{DisplayControl: 0},
	{DisplayTitle: 0},
	{deleteOnBossDeath: 0},
	{invisibleOnBossDeath: 0},
	{Death: 0},
	{Touch: 0},
	{Gamepad: 0},
	{DisplayTitle2: 0},
	{DisplayTitle3: 0},
	{Browser: 0},
	{DisplayControl2: 0},
	{SpriteFontDeaths: 0},
	{SpriteFontIconDeaths: 0},
	{SpriteFontIconTime: 0},
	{SpriteFontTiime: 0},
	{distance: 0},
	{enabledBySaveUID: 0},
	{startX: 0},
	{startY: 0},
	{INVERTED: 0},
	{Death2MovingLava: 0},
	{DisplayTitle6: 0},
	{WallTilemap: 0},
	{GridDev: 0},
	{speedX: 0},
	{speedY: 0},
	{TractorBeam: 0},
	{save: 0},
	{startFinalCountdown: 0},
	{DevPoint: 0},
	{WallDestructible: 0},
	{PIERCING: 0},
	{BOUNCY: 0},
	{Fly: 0},
	{type: 0},
	{ShouldMove: 0},
	{Portal: 0},
	{activationRadius: 0},
	{Death3LerpBall: 0},
	{targetObjectInsteadOfBullet: 0},
	{imagepoint: 0},
	{Zap: 0},
	{TouchLeft: 0},
	{TouchRight: 0},
	{Collectible: 0},
	{horizontal: 0},
	{hp: 0},
	{maxHp: 0},
	{multiswitch: 0},
	{Door: 0},
	{DoorUid: 0},
	{timeout: 0},
	{vertical: 0},
	{reverse: 0},
	{DOOR_X: 0},
	{DOOR_Y: 0},
	{special: 0},
	{DoorOpener: 0},
	{enabledBySaveUid: 0},
	{enabled: 0},
	{STARTX: 0},
	{STARTY: 0},
	{initialAngle: 0},
	{idleSpeed: 0},
	{attackSpeed: 0},
	{attackDuration: 0},
	{attackInterval: 0},
	{INITIAL_HP: 0},
	{openDoorUidOnDeath: 0},
	{reverseOpenDoorDirection: 0},
	{shootsBullets: 0},
	{shootAmount: 0},
	{shootdelay: 0},
	{horizontalDoorOpen: 0},
	{SPEED: 0},
	{MOVING: 0},
	{damageTakenFromZombie: 0},
	{imuneAgainstPlayerBullets: 0},
	{Boss: 0},
	{Audio: 0},
	{Jumpthru: 0},
	{WallThru: 0},
	{activationDistance: 0},
	{jumpActivationRange: 0},
	{deactivationRange: 0},
	{TackleJumpStrength: 0},
	{openDoor: 0},
	{STUNNED: 0},
	{Platform: 0},
	{Zombie: 0},
	{LocalStorage: 0},
	{Shoot: 0},
	{Explode: 0},
	{ZombieKiller: 0},
	{TextScrollable: 0},
	{Pin: 0},
	{TextSpriteFontBg: 0},
	{SpriteFont2: 0},
	{text: 0},
	{TextTrigger: 0},
	{uidToDestroy: 0},
	{DevComment: 0},
	{Destroyer: 0},
	{NewGame: 0},
	{LoadGame: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{SpriteFontCollectibles: 0},
	{SpriteFontIconDeaths2: 0},
	{BossHpBg: 0},
	{BossHpFg: 0},
	{deaths: 0},
	{time: 0},
	{finalCountdownStarted: 0},
	{FinalCountdownTimer: 0},
	{diedInFinalRoom: 0},
	{Globals: 0},
	{VideoRecorder: 0},
	{AJAX: 0},
	{Blunderbuss: 0},
	{TextSpriteFont2: 0},
	{Teleporter: 0},
	{Zap2: 0},
	{Toll: 0},
	{DoorCollectibles: 0},
	{regenTime: 0},
	{WallDestructibleRegen: 0},
	{Water: 0},
	{TextTriggerToll: 0},
	{DeathToInvert: 0},
	{InverterSwitch: 0},
	{WaterUID: 0},
	{WaterX: 0},
	{WaterY: 0},
	{WaterFlooder: 0},
	{prop_sign_exit: 0},
	{prop_portal: 0},
	{ActivateTag: 0},
	{JumpSineStarter: 0},
	{DeathSineStarter: 0},
	{DeathSineStopper: 0},
	{WaterSineStarter: 0},
	{Particles: 0},
	{ParcticlesCollect: 0},
	{BossBullet: 0},
	{Text: 0},
	{ExitToMenu: 0},
	{ResumeGame: 0},
	{ConfirmOverride: 0},
	{CancelOverride: 0},
	{pausebutton: 0},
	{FinalCountdown: 0},
	{RocketJump: 0},
	{OpenDoorUidOnDeath: 0},
	{delaytoMoveAfterShoot: 0},
	{zipLeftWhenDead: 0},
	{zipDownWhenDead: 0},
	{attackShootToggle: 0},
	{disableAttack: 0},
	{shootRepeat: 0},
	{shootRepeatInterval: 0},
	{shootRepeatRotation: 0},
	{StartAngleFixed: 0},
	{fixedStartAngle: 0},
	{fastIntro: 0},
	{deleteMusicTriggerOnDeath: 0},
	{triggerIntroOnDeath: 0},
	{triggerLoopOnDeath: 0},
	{achievmentName: 0},
	{BossBig: 0},
	{BossSmall: 0},
	{introtextfield: 0},
	{introfrontface: 0},
	{introfar1: 0},
	{introfar2: 0},
	{introfar3: 0},
	{introside: 0},
	{introgun: 0},
	{IntroBackground: 0},
	{introeyes: 0},
	{introWhiteFlash: 0},
	{introfar0: 0},
	{FADEIN: 0},
	{introBlackFade: 0},
	{necro64Intro: 0},
	{introfarsad: 0},
	{introbaldsad: 0},
	{introdooropening: 0},
	{introheroclose: 0},
	{introhug: 0},
	{introhand: 0},
	{introleaving: 0},
	{introTheEnd: 0},
	{Function: 0},
	{introtextfield2: 0},
	{introtextfield3: 0},
	{blackfade: 0},
	{NoPause: 0},
	{BossFinal2: 0},
	{FinalBossArea: 0},
	{TextVersion: 0},
	{Effector: 0},
	{Death2MovingLavaDiamond: 0},
	{BossSmall2: 0},
	{CheckpointUID: 0},
	{CheckpointActivatorTrigger: 0},
	{frame: 0},
	{MINIMAP: 0},
	{biggerminimap: 0},
	{intro: 0},
	{loop: 0},
	{fadein: 0},
	{MusicTrigger: 0},
	{anypixelanim: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{MinimapEnabler: 0},
	{MinimapDot: 0},
	{MinimapDot2: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{MinimapDot3: 0},
	{Greenworks: 0},
	{name: 0},
	{achievmentTrigger: 0},
	{Mouse: 0},
	{Destroyables: 0},
	{bossFamily: 0},
	{timee: 0},
	{temp: 0},
	{temp2: 0},
	{temp3: 0},
	{temp4: 0},
	{temp5: 0},
	{activeGamepadId: 0},
	{temp6: 0},
	{temp7: 0},
	{collectibles: 0},
	{finalCountdownTimer: 0},
	{finalCountdownTimerFast: 0},
	{collectiblesToCountFast: 0},
	{saveUid: 0},
	{isTouchingLeft: 0},
	{isTouchingRight: 0},
	{muteSFX: 0},
	{muteSound: 0},
	{PAUSED: 0},
	{IntroFinished: 0},
	{recordingURL: 0},
	{effectorActivated: 0},
	{minimapX: 0},
	{minimapY: 0},
	{lastMusicTriggerHit: 0},
	{lastMusicTriggerWasBoss: 0},
	{startLoopAfterCurrentTrack: 0},
	{loopToStart: 0},
	{soundtrackVolume: 0},
	{nowPlaying: 0},
	{PAUSED2: 0},
	{uid: 0},
	{CurrentScrollX: 0},
	{CurrentScrollY: 0},
	{length: 0},
	{x: 0},
	{y: 0},
	{offset: 0},
	{repeatIndeX: 0},
	{TollValue: 0},
	{FinalCollectibles: 0},
	{FinalTime: 0},
	{FinalDeaths: 0},
	{canFinish: 0},
	{deadzone: 0}
];

self.InstanceType = {
	crono: class extends self.ISpriteInstance {},
	skully: class extends self.ISpriteInstance {},
	skully2: class extends self.ISpriteInstance {},
	CollectibleIcon: class extends self.ISpriteInstance {},
	Necrotitle: class extends self.ISpriteInstance {},
	loadicon: class extends self.ISpriteInstance {},
	newicon: class extends self.ISpriteInstance {},
	buttonmapicon: class extends self.ISpriteInstance {},
	bigarrow: class extends self.ISpriteInstance {},
	prop_text_heaven: class extends self.ISpriteInstance {},
	prop_text_afterlife: class extends self.ISpriteInstance {},
	prop_count1: class extends self.ISpriteInstance {},
	prop_text_block: class extends self.ISpriteInstance {},
	prop_text_tower: class extends self.ISpriteInstance {},
	prop_text_chasm: class extends self.ISpriteInstance {},
	prop_chain_big: class extends self.ITiledBackgroundInstance {},
	prop_text_limbo: class extends self.ISpriteInstance {},
	prop_flooded: class extends self.ISpriteInstance {},
	prop_line1: class extends self.ISpriteInstance {},
	BGDogTooth: class extends self.ITiledBackgroundInstance {},
	BGSomething: class extends self.ITiledBackgroundInstance {},
	BGSomething2: class extends self.ITiledBackgroundInstance {},
	BGSomething3: class extends self.ITiledBackgroundInstance {},
	smallarrow: class extends self.ISpriteInstance {},
	PauseQuit: class extends self.ISpriteInstance {},
	PauseResume: class extends self.ISpriteInstance {},
	PauseTitle: class extends self.ISpriteInstance {},
	Confirm: class extends self.ISpriteInstance {},
	ConfirmYes: class extends self.ISpriteInstance {},
	ConfirmNo: class extends self.ISpriteInstance {},
	prop_text_heaven2: class extends self.ISpriteInstance {},
	FakeWall: class extends self.ITiledBackgroundInstance {},
	prop_giveup: class extends self.ISpriteInstance {},
	prop_uarrow: class extends self.ISpriteInstance {},
	skully3: class extends self.ISpriteInstance {},
	prop_web: class extends self.ISpriteInstance {},
	prop_spinner: class extends self.ISpriteInstance {},
	prop_bunting: class extends self.ITiledBackgroundInstance {},
	prop_spinner_small: class extends self.ISpriteInstance {},
	prop_fakewall: class extends self.ISpriteInstance {},
	prop_text_goback: class extends self.ISpriteInstance {},
	prop_text_welcome: class extends self.ISpriteInstance {},
	prop_yourehere: class extends self.ISpriteInstance {},
	SplashBG: class extends self.ISpriteInstance {},
	SplashBGFlash: class extends self.ISpriteInstance {},
	prop_text_the_well: class extends self.ISpriteInstance {},
	DevNotes: class extends self.ITextInstance {},
	CreditsText: class extends self.ISpriteFontInstance {},
	creditscamera: class extends self.ISpriteInstance {},
	CreditsRollStopper: class extends self.ISpriteInstance {},
	WhiteScreen: class extends self.ITiledBackgroundInstance {},
	BlackCurtain: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	End: class extends self.ISpriteInstance {},
	Jump: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Spawn: class extends self.ISpriteInstance {},
	DisplayControl: class extends self.ISpriteInstance {},
	DisplayTitle: class extends self.ISpriteInstance {},
	Death: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	DisplayTitle2: class extends self.ISpriteInstance {},
	DisplayTitle3: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	DisplayControl2: class extends self.ISpriteInstance {},
	SpriteFontDeaths: class extends self.ISpriteFontInstance {},
	SpriteFontIconDeaths: class extends self.ISpriteInstance {},
	SpriteFontIconTime: class extends self.ISpriteInstance {},
	SpriteFontTiime: class extends self.ISpriteFontInstance {},
	Death2MovingLava: class extends self.ISpriteInstance {},
	DisplayTitle6: class extends self.ISpriteInstance {},
	WallTilemap: class extends self.ITilemapInstance {},
	GridDev: class extends self.ITiledBackgroundInstance {},
	TractorBeam: class extends self.ITiledBackgroundInstance {},
	DevPoint: class extends self.ISpriteInstance {},
	WallDestructible: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Fly: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Death3LerpBall: class extends self.ISpriteInstance {},
	Zap: class extends self.ISpriteInstance {},
	TouchLeft: class extends self.ISpriteInstance {},
	TouchRight: class extends self.ISpriteInstance {},
	Collectible: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	DoorOpener: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	WallThru: class extends self.ISpriteInstance {},
	Zombie: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Shoot: class extends self.ISpriteInstance {},
	Explode: class extends self.ISpriteInstance {},
	ZombieKiller: class extends self.ISpriteInstance {},
	TextScrollable: class extends self.ISpriteFontInstance {},
	TextSpriteFontBg: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	TextTrigger: class extends self.ISpriteInstance {},
	Destroyer: class extends self.ISpriteInstance {},
	NewGame: class extends self.ISpriteInstance {},
	LoadGame: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	SpriteFontCollectibles: class extends self.ISpriteFontInstance {},
	SpriteFontIconDeaths2: class extends self.ISpriteInstance {},
	BossHpBg: class extends self.ISpriteInstance {},
	BossHpFg: class extends self.ISpriteInstance {},
	Globals: class extends self.ISpriteInstance {},
	VideoRecorder: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Blunderbuss: class extends self.ISpriteInstance {},
	TextSpriteFont2: class extends self.ISpriteFontInstance {},
	Teleporter: class extends self.ISpriteInstance {},
	Zap2: class extends self.ISpriteInstance {},
	DoorCollectibles: class extends self.ISpriteInstance {},
	WallDestructibleRegen: class extends self.ISpriteInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	TextTriggerToll: class extends self.ISpriteInstance {},
	InverterSwitch: class extends self.ISpriteInstance {},
	WaterFlooder: class extends self.ITiledBackgroundInstance {},
	prop_sign_exit: class extends self.ISpriteInstance {},
	prop_portal: class extends self.ISpriteInstance {},
	JumpSineStarter: class extends self.ITiledBackgroundInstance {},
	DeathSineStarter: class extends self.ITiledBackgroundInstance {},
	DeathSineStopper: class extends self.ITiledBackgroundInstance {},
	WaterSineStarter: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	ParcticlesCollect: class extends self.IParticlesInstance {},
	BossBullet: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	ExitToMenu: class extends self.ISpriteInstance {},
	ResumeGame: class extends self.ISpriteInstance {},
	ConfirmOverride: class extends self.ISpriteInstance {},
	CancelOverride: class extends self.ISpriteInstance {},
	pausebutton: class extends self.ISpriteInstance {},
	FinalCountdown: class extends self.ISpriteFontInstance {},
	RocketJump: class extends self.ISpriteInstance {},
	BossBig: class extends self.ISpriteInstance {},
	BossSmall: class extends self.ISpriteInstance {},
	introtextfield: class extends self.ITextInstance {},
	introfrontface: class extends self.ISpriteInstance {},
	introfar1: class extends self.ISpriteInstance {},
	introfar2: class extends self.ISpriteInstance {},
	introfar3: class extends self.ISpriteInstance {},
	introside: class extends self.ISpriteInstance {},
	introgun: class extends self.ISpriteInstance {},
	IntroBackground: class extends self.ITiledBackgroundInstance {},
	introeyes: class extends self.ISpriteInstance {},
	introWhiteFlash: class extends self.ITiledBackgroundInstance {},
	introfar0: class extends self.ISpriteInstance {},
	introBlackFade: class extends self.ITiledBackgroundInstance {},
	necro64Intro: class extends self.ISpriteInstance {},
	introfarsad: class extends self.ISpriteInstance {},
	introbaldsad: class extends self.ISpriteInstance {},
	introdooropening: class extends self.ISpriteInstance {},
	introheroclose: class extends self.ISpriteInstance {},
	introhug: class extends self.ISpriteInstance {},
	introhand: class extends self.ISpriteInstance {},
	introleaving: class extends self.ISpriteInstance {},
	introTheEnd: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	introtextfield2: class extends self.ISpriteFontInstance {},
	introtextfield3: class extends self.ISpriteFontInstance {},
	blackfade: class extends self.ISpriteInstance {},
	NoPause: class extends self.ISpriteInstance {},
	BossFinal2: class extends self.ISpriteInstance {},
	FinalBossArea: class extends self.ISpriteInstance {},
	TextVersion: class extends self.ISpriteFontInstance {},
	Effector: class extends self.ISpriteInstance {},
	Death2MovingLavaDiamond: class extends self.ISpriteInstance {},
	BossSmall2: class extends self.ISpriteInstance {},
	CheckpointActivatorTrigger: class extends self.ISpriteInstance {},
	frame: class extends self.ISpriteInstance {},
	MINIMAP: class extends self.ISpriteInstance {},
	biggerminimap: class extends self.ISpriteInstance {},
	MusicTrigger: class extends self.ISpriteInstance {},
	anypixelanim: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MinimapEnabler: class extends self.ISpriteInstance {},
	MinimapDot: class extends self.ISpriteInstance {},
	MinimapDot2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	MinimapDot3: class extends self.ISpriteInstance {},
	Greenworks: class extends self.IInstance {},
	achievmentTrigger: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Destroyables: class extends self.ISpriteInstance {},
	bossFamily: class extends self.ISpriteInstance {}
}