const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.Tilemap,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Spritefont2.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{immovable: 0},
	{attached: 0},
	{hinged: 0},
	{hingeId: 0},
	{hingeDistance: 0},
	{windEmitter: 0},
	{windRange: 0},
	{windStrength: 0},
	{rocket: 0},
	{rocketStrength: 0},
	{movable: 0},
	{startX: 0},
	{startY: 0},
	{player: 0},
	{end: 0},
	{Cursor: 0},
	{Mouse: 0},
	{Pin: 0},
	{Fade: 0},
	{CursorRange: 0},
	{hinge: 0},
	{Tilemap: 0},
	{Sprite: 0},
	{Tilemap2: 0},
	{Msg: 0},
	{guideId: 0},
	{MsgToggle: 0},
	{Text: 0},
	{Sprite2: 0},
	{strength: 0},
	{Wind: 0}
];

self.InstanceType = {
	immovable: class extends self.ISpriteInstance {},
	movable: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	CursorRange: class extends self.ISpriteInstance {},
	hinge: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Msg: class extends self.ISpriteFontInstance {},
	MsgToggle: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Wind: class extends self.ISpriteInstance {}
}